#cargo-features = ["strip"]

[package]
name = "amd-gpu-fan-daemon"
version = "0.1.0"
edition = "2021"


[dependencies]
device = {path = "src/device"}
config = {path = "src/config"}

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
#strip = true
